<a href="https://colab.research.google.com/github/jenish2/032_Jenish_Dholariya/blob/main/Lab_01_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd

In [4]:
# two matrics
array1 = np.array([[4, 8, 1],[8, 7, 4]])
array2 = np.array([[5,-9],[1, 4],[7, -3]])
print(array1)
print(array2)

[[4 8 1]
 [8 7 4]]
[[ 5 -9]
 [ 1  4]
 [ 7 -3]]


In [6]:
#randomly initialize array
array = np.random.rand(3, 4)
print(array)

[[0.015106   0.33958534 0.19588285 0.06523707]
 [0.3625899  0.42672001 0.30918921 0.82174373]
 [0.9070511  0.87537734 0.22164099 0.88723292]]


In [7]:
# perform matrix multiplication
mul = np.dot(array1, array2)
print(mul)

[[ 35  -7]
 [ 75 -56]]


In [8]:
# perform element wise matrix multiplication
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res)

[[35, -7], [75, -56]]


In [9]:
# mean of first matrix
mean = np.mean(array1)
print(mean)

5.333333333333333


In [10]:
main_data= pd.read_csv("/content/drive/MyDrive/Semester7/ML/Lab01/Exercise-CarData.csv")